# -*- coding: utf-8 -*-
"""DOGBTI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IRvSGTxpDdUG0B-t19Dat2QyM8UrBiGq
"""

# DOGBTI

import streamlit as st

# 제목 이미지 띄우기 (images/title.png 경로 예시)
st.image("dog_images/멍BTI 사진.png", use_column_width=True)

# 기존 질문 리스트 (수정 없이 유지)
questions = [
    ["1번 : 산책 나가면?", "1. 사람, 강아지에게 먼저 다가간다", "2. 조용히 집사 곁에만 맴돈다", "EI","dog_images/개냥이.png"],
    ["2번 : 새로운 장난감 반응?", "1. 금방 호기심, 바로 입에 물어본다.", "2. 신중하게 냄새 맡고 관찰", "NS","dog_images/뼈다귀 문 강아지.png"],
    ["3번 : 혼자 있을 때?", "1. 장난감, 창밖 구경, 탐색한다", "2. 주로 자거나 한 곳에서 쉰다", "PJ","dog_images/시바견 사진.png"],
    ["4번 : 낯선 강아지와 만남?", "1. 적극적으로 다가가서 논다", "2. 경계하거나 집사 뒤에 숨는다", "EI","dog_images/어울리는 강아지.png"],
    ["5번 : 간식 줄 때?", "1. 바로 먹고 더 달라고 애교 부린다.", "2. 침착하게 기다리거나 아껴 먹음", "FT","dog_images/파블로프 강아지.png"],
    ["6번 : 집사와 놀이 시간?", "1. 다양한 장난감과 놀이 좋아함", "2. 익숙한 놀이만 반복", "NS","dog_images/뛰는 강아지.png"],
    ["7번 : 혼날 때 반응?", "1. 금방 풀리고 애교부림", "2. 빠지거나 한동안 숨음", "FT","dog_images/뽀글머리 강아지.png"],
    ["8번 : 산책할 때 리드줄 텐션은?", "1. 끌고 다니거나 앞장서는 타입", "2. 집사 곁을 조용히 걷는 타입", "PJ","dog_images/강아지 산책 사진.png"]
]

# 점수 초기화
scores = {
    "EI": 0,  # +1이면 E, -1이면 I
    "NS": 0,  # +1이면 N, -1이면 S
    "FT": 0,  # +1이면 F, -1이면 T
    "PJ": 0   # +1이면 P, -1이면 J
}

# 질문에 대한 사용자 응답 받기
for i, q in enumerate(questions):
    st.write(f"**{q[0]}**")
    col1, col2 = st.columns(2)
    with col1:
        if st.button(q[1], key=f"{i}_1"):
            scores[q[3]] += 1
    with col2:
        if st.button(q[2], key=f"{i}_2"):
            scores[q[3]] -= 1

# 결과 버튼
if st.button("결과 보기 🐾"):
    mbti = ''
    mbti += 'E' if scores['EI'] >= 0 else 'I'
    mbti += 'N' if scores['NS'] >= 0 else 'S'
    mbti += 'F' if scores['FT'] >= 0 else 'T'
    mbti += 'P' if scores['PJ'] >= 0 else 'J'

    st.header(f"🐶 당신 강아지의 멍BTI는 {mbti} 입니다!")

    # MBTI별 설명 & 추천 제품 (이미지 주소는 예시)
    mbti_descriptions = {
        "ESTJ": "성실하고 활동적인 리더형 멍멍이!",
        "ESFJ": "사랑이 넘치고 사교성 좋은 가족형 멍멍이!",
        "ISTJ": "차분하고 신중한 계획가 멍멍이!",
        "ISFJ": "다정하고 보호 본능 강한 힐러 멍멍이!",
        "ESTP": "모험심 가득한 활발한 탐험가 멍멍이!",
        "ESFP": "장난꾸러기 즐거운 파티 멍멍이!",
        "ISTP": "침착하고 관찰력 뛰어난 해결사 멍멍이!",
        "ISFP": "감성적이고 조용한 예술가 멍멍이!",
        "ENFJ": "따뜻한 리더십으로 친구들을 이끄는 멍멍이!",
        "ENTJ": "똑똑하고 자신감 넘치는 전략가 멍멍이!",
        "INFJ": "조용하지만 깊은 마음을 가진 사려 깊은 멍멍이!",
        "INTJ": "논리적이고 독립적인 천재 멍멍이!",
        "ENFP": "상상력이 풍부하고 활발한 아이디어 뱅크 멍멍이!",
        "ENTP": "재치 있고 논쟁을 즐기는 토론가 멍멍이!",
        "INFP": "순수하고 이상주의적인 꿈꾸는 멍멍이!",
        "INTP": "분석적이고 호기심 많은 탐구자 멍멍이!"

        "
    }

    product_recommendations = {
        "ESTJ": {
            "image": "dog_images/glorious.webp",
            "desc": "활동적인 ESTJ에게는 우아한 Glorious를 추천합니다!"
        },
        "ESFJ": {
            "image": "dog_images/glorious.webp",
            "desc": "사교성 좋은 ESFJ에게는 우아한 향기의 Glorious를 추천합니다!"
        },
        "ISTJ": {
            "image": "dog_images/adventurous.webp",
            "desc": "차분한 ISFJ에게는 시원한 향기의 Adventurous를 추천합니다!"
        },
        "ISFJ": {
            "image": "dog_images/adventurous.webp",
            "desc": "차분한 ISFJ에게는 시원한 향기의 Adventurous를 추천합니다!"
        },
        "ESTP": {
            "image": "dog_images/glorious.webp",
            "desc": "차분한 ESTP에게는 우아한 향기의 Glorious를 추천합니다!"
        },
        "ESFP": {
            "image": "dog_images/harmonious.webp",
            "desc": "차분한 ESFP에게는 은은한 향기의 Harmonious를 추천합니다!"
        },
        "ISTP": {
            "image": "dog_images/adventurous.webp",
            "desc": "차분한 ISTP에게는 시원한 향기의 Adventurous를 추천합니다!"
        },
        "ISFP": {
            "image": "dog_images/harmonious.webp",
            "desc": "차분한 ISFP에게는 은은한 향기의 Harmonious를 추천합니다!"
        },
        "ENFJ": {
            "image": "dog_images/adventurous.webp",
            "desc": "차분한 ENFJ에게는 시원한 향기의 Adventurous를 추천합니다!"
        },
        "ENTJ": {
            "image": "dog_images/harmonious.webp",
            "desc": "차분한 ENTJ에게는 은은한 향기의 Harmonious를 추천합니다!"
        },
        "INFJ": {
            "image": "dog_images/glorious.webp",
            "desc": "차분한 INFJ에게는 우아한 향기의 Glorious를 추천합니다!"
        },
        "INTJ": {
            "image": "dog_images/glorious.webp",
            "desc": "차분한 INTJ에게는 우아한 향기의 Glorious를 추천합니다!"
        },
        "ENFP": {
            "image": "dog_images/adventurous.webp",
            "desc": "차분한 ENFP에게는 시원한 향기의 Adventurous를 추천합니다!"
        },
        "ENTP": {
            "image": "dog_images/harmonious.webp",
            "desc": "차분한 ENTP에게는 은은한 향기의 Harmonious를 추천합니다!"
        },
        "INFP": {
            "image": "dog_images/adventurous.webp",
            "desc": "차분한 INFP에게는 시원한 향기의 Adventurous를 추천합니다!"
        },
        "INTP": {
            "image": "dog_images/harmonious.webp",
            "desc": "차분한 INTP에게는 은은한 향기의 Harmonious를 추천합니다!"
        }


    }

    if mbti in mbti_descriptions:
        st.markdown(f"**{mbti_descriptions[mbti]}**")
    else:
        st.write("아직 설명이 준비되지 않았어요!")

    if mbti in product_recommendations:
        st.image(product_recommendations[mbti]["image"], use_column_width=True)
        st.markdown(product_recommendations[mbti]["desc"])
    else:
        st.write("추천 제품 정보가 아직 없습니다.")